<a href="https://colab.research.google.com/github/Trickwillfrit/Sustainable-logistics/blob/main/Logistics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
distance_url = "https://raw.githubusercontent.com/Trickwillfrit/sustainable-logistics/main/Distance_matrix.csv"
population_url = "https://raw.githubusercontent.com/Trickwillfrit/sustainable-logistics/main/Pop_district.xlsx"

In [ ]:
import pandas as pd
import numpy as np

distance_df = pd.read_csv(distance_url, encoding='latin1')
population_df = pd.read_excel(population_url, sheet_name="Total")

print(distance_df.shape)
print(population_df.shape)

display(distance_df.head())
display(population_df.head())

(300, 52)
(312, 12)

,I,ID,Aigle Pôle Physio-Ergo d'Aigle,Biotonus,CIC,Centre Hospitalier Universitaire Vaudois,Chamoyron,Château-d'Oex,Clinique Bois-Bougy,Clinique Bois-Cerf,...,Mottex Réadaptation/gériatrie,Moudon,Payerne,Permanence de Cossonay,Providence Permanence médicale Riviera Réadaptation/gériatrie,Psychiatrie Nord CPNVD,Psychiatrie Ouest Hôpital de Prangins,Pôle Santé Pays-d'Enhaut,Rennaz Centre hospitalier de Rennaz,Samaritain Site administratif
0,177,Aclens,45246.942980,34922.87591,32420.85619,10927.39241,30067.65535,48354.90528,30587.908920,11019.19780,...,31051.46560,25004.00878,43505.62437,5281.689022,29000.64891,26094.04433,27024.823580,49340.96733,37753.763050,28881.46539
1,179,Agiez,57570.916270,45097.04257,42668.61132,23846.87021,39573.64688,54700.99056,44112.448860,24872.27358,...,40740.99966,23071.54294,35189.23270,11695.532970,39316.62263,12680.75438,40558.090660,55378.40648,49257.260150,39076.37149
2,0,Aigle,1032.805771,12806.69036,14708.57744,33771.21417,18088.76873,21368.31674,56695.504070,33352.86014,...,16930.04614,40987.10347,55753.59043,48135.994080,17633.70500,56957.07744,54895.747330,22576.73176,7553.029716,17932.74595
3,178,Allaman,47522.552800,40642.39135,38374.06615,19801.74039,37039.86552,56205.38763,16691.436870,18734.80193,...,37720.58416,38296.57183,57357.87610,18123.526940,35369.96791,39739.48966,13193.869580,57358.33950,41726.331610,35386.76027
4,176,Arnex-sur-Nyon,60116.786400,56346.85466,54368.17988,38281.18622,53708.34720,72658.66608,2880.205603,37046.22329,...,54179.94863,57159.98724,76066.93858,35891.212900,51804.65180,57229.74102,5726.631365,73890.44347,56137.013200,51896.45023

,District,Mesures,Unnamed: 2,Population au 31.12.,Population au 31.12..1,Population au 31.12..2,Population au 31.12..3,Population au 31.12..4,Population au 31.12..5,Population au 31.12..6,Population au 31.12..7,Population au 31.12..8
0,Morges,Aclens,5621.0,545,535,539,528,517,557,578,587,609
1,Jura-Nord vaudois,Agiez,5742.0,314,327,354,377,375,381,383,373,382
2,Aigle,Aigle,5401.0,10153,10134,10217,10518,10823,10937,11437,11780,12081
3,Morges,Allaman,5851.0,442,434,451,443,430,420,431,430,412
4,Nyon,Arnex-sur-Nyon,5701.0,224,235,229,240,226,240,242,267,274

In [ ]:
# Basic information about the two datasets

print("Distance matrix shape:", distance_df.shape)
print("Population data shape:", population_df.shape)

print("\nDistance matrix columns:")
print(distance_df.columns.tolist())

print("\nPopulation data columns:")
print(population_df.columns.tolist())

print("\nFirst rows of distance matrix:")
display(distance_df.head())

print("\nFirst rows of population data:")
display(population_df.head())

Distance matrix shape: (300, 52)
Population data shape: (312, 12)

Distance matrix columns:
['I', 'ID', "Aigle Pôle Physio-Ergo d'Aigle", 'Biotonus', 'CIC', 'Centre Hospitalier Universitaire Vaudois', 'Chamoyron', "Château-d'Oex", 'Clinique Bois-Bougy', 'Clinique Bois-Cerf', 'Clinique Cecil', 'Clinique La Prairie', 'Clinique Valmont', 'Clinique de Genolier', 'Clinique de Montchoisi', 'Clinique de la Source', 'Clinique la Lignière', 'Clinique la Métairie', 'Espace Santé Rennaz', 'Fondation Rive-Neuve', 'Grand-Chêne', 'HRC', "Hôpital d'Orbe", "Hôpital d'Yverdon-les-Bains", 'Hôpital de Chamblon', 'Hôpital de Gilly', 'Hôpital de Lavaux', 'Hôpital de Morges', 'Hôpital de Nyon', 'Hôpital de Rolle', 'Hôpital de Saint-Loup', 'Hôpital de la VallÃ©e de Joux', 'Hôpital ophtalmique Jules-Gonin', 'Hôpital psychiatrique Nant', "Hôpital d'Aubonne", 'Institution de Lavigny', 'La Tour-de-Peilz', 'Les Communaux', 'Les Moulins', 'Les Rosiers', 'Molage', 'Montreux', 'Mottex Réadaptation/gériatrie', 'Moudon', 'Payerne', 'Permanence de Cossonay', 'Providence Permanence médicale Riviera Réadaptation/gériatrie', 'Psychiatrie Nord CPNVD', 'Psychiatrie Ouest Hôpital de Prangins', "Pôle Santé Pays-d'Enhaut", 'Rennaz Centre hospitalier de Rennaz', 'Samaritain Site administratif']

Population data columns:
['District ', 'Mesures', 'Unnamed: 2', 'Population au 31.12.', 'Population au 31.12..1', 'Population au 31.12..2', 'Population au 31.12..3', 'Population au 31.12..4', 'Population au 31.12..5', 'Population au 31.12..6', 'Population au 31.12..7', 'Population au 31.12..8']

First rows of distance matrix:

,I,ID,Aigle Pôle Physio-Ergo d'Aigle,Biotonus,CIC,Centre Hospitalier Universitaire Vaudois,Chamoyron,Château-d'Oex,Clinique Bois-Bougy,Clinique Bois-Cerf,...,Mottex Réadaptation/gériatrie,Moudon,Payerne,Permanence de Cossonay,Providence Permanence médicale Riviera Réadaptation/gériatrie,Psychiatrie Nord CPNVD,Psychiatrie Ouest Hôpital de Prangins,Pôle Santé Pays-d'Enhaut,Rennaz Centre hospitalier de Rennaz,Samaritain Site administratif
0,177,Aclens,45246.942980,34922.87591,32420.85619,10927.39241,30067.65535,48354.90528,30587.908920,11019.19780,...,31051.46560,25004.00878,43505.62437,5281.689022,29000.64891,26094.04433,27024.823580,49340.96733,37753.763050,28881.46539
1,179,Agiez,57570.916270,45097.04257,42668.61132,23846.87021,39573.64688,54700.99056,44112.448860,24872.27358,...,40740.99966,23071.54294,35189.23270,11695.532970,39316.62263,12680.75438,40558.090660,55378.40648,49257.260150,39076.37149
2,0,Aigle,1032.805771,12806.69036,14708.57744,33771.21417,18088.76873,21368.31674,56695.504070,33352.86014,...,16930.04614,40987.10347,55753.59043,48135.994080,17633.70500,56957.07744,54895.747330,22576.73176,7553.029716,17932.74595
3,178,Allaman,47522.552800,40642.39135,38374.06615,19801.74039,37039.86552,56205.38763,16691.436870,18734.80193,...,37720.58416,38296.57183,57357.87610,18123.526940,35369.96791,39739.48966,13193.869580,57358.33950,41726.331610,35386.76027
4,176,Arnex-sur-Nyon,60116.786400,56346.85466,54368.17988,38281.18622,53708.34720,72658.66608,2880.205603,37046.22329,...,54179.94863,57159.98724,76066.93858,35891.212900,51804.65180,57229.74102,5726.631365,73890.44347,56137.013200,51896.45023

First rows of population data:

,District,Mesures,Unnamed: 2,Population au 31.12.,Population au 31.12..1,Population au 31.12..2,Population au 31.12..3,Population au 31.12..4,Population au 31.12..5,Population au 31.12..6,Population au 31.12..7,Population au 31.12..8
0,Morges,Aclens,5621.0,545,535,539,528,517,557,578,587,609
1,Jura-Nord vaudois,Agiez,5742.0,314,327,354,377,375,381,383,373,382
2,Aigle,Aigle,5401.0,10153,10134,10217,10518,10823,10937,11437,11780,12081
3,Morges,Allaman,5851.0,442,434,451,443,430,420,431,430,412
4,Nyon,Arnex-sur-Nyon,5701.0,224,235,229,240,226,240,242,267,274

In [ ]:
# --- Clean distance matrix ---

# Drop useless index column if it exists
distance_clean = distance_df.drop(columns=["I"], errors="ignore").copy()

# Rename commune column
distance_clean = distance_clean.rename(columns={"ID": "commune"})

# Remove spaces before/after commune names
distance_clean["commune"] = distance_clean["commune"].astype(str).str.strip()

# Fix one remaining encoding issue in hospital name
distance_clean = distance_clean.rename(
    columns={"Hôpital de la VallÃ©e de Joux": "Hôpital de la Vallée de Joux"}
)

# Identify hospital columns
hospital_cols = [col for col in distance_clean.columns if col != "commune"]


# --- Clean population data ---

population_clean = population_df.copy()

# Keep only real commune rows: rows where the commune code exists
population_clean = population_clean[population_clean["Unnamed: 2"].notna()].copy()

# Keep useful columns only
population_clean = population_clean[
    ["District ", "Mesures", "Unnamed: 2", "Population au 31.12..8"]
].copy()

# Rename columns
population_clean = population_clean.rename(
    columns={
        "District ": "district",
        "Mesures": "commune",
        "Unnamed: 2": "commune_code",
        "Population au 31.12..8": "population_2025"
    }
)

# Clean commune names
population_clean["commune"] = population_clean["commune"].astype(str).str.strip()

# Make population numeric
population_clean["population_2025"] = pd.to_numeric(
    population_clean["population_2025"], errors="coerce"
)


# --- Print results ---

print("Distance clean shape:", distance_clean.shape)
print("Population clean shape:", population_clean.shape)

print("\nNumber of communes in distance matrix:", distance_clean["commune"].nunique())
print("Number of communes in population file:", population_clean["commune"].nunique())

print("\nNumber of hospitals:", len(hospital_cols))

print("\nDistance clean preview:")
display(distance_clean.head())

print("\nPopulation clean preview:")
display(population_clean.head())

Distance clean shape: (300, 51)
Population clean shape: (300, 4)

Number of communes in distance matrix: 300
Number of communes in population file: 300

Number of hospitals: 50

Distance clean preview:

,commune,Aigle Pôle Physio-Ergo d'Aigle,Biotonus,CIC,Centre Hospitalier Universitaire Vaudois,Chamoyron,Château-d'Oex,Clinique Bois-Bougy,Clinique Bois-Cerf,Clinique Cecil,...,Mottex Réadaptation/gériatrie,Moudon,Payerne,Permanence de Cossonay,Providence Permanence médicale Riviera Réadaptation/gériatrie,Psychiatrie Nord CPNVD,Psychiatrie Ouest Hôpital de Prangins,Pôle Santé Pays-d'Enhaut,Rennaz Centre hospitalier de Rennaz,Samaritain Site administratif
0,Aclens,45246.942980,34922.87591,32420.85619,10927.39241,30067.65535,48354.90528,30587.908920,11019.19780,9966.296368,...,31051.46560,25004.00878,43505.62437,5281.689022,29000.64891,26094.04433,27024.823580,49340.96733,37753.763050,28881.46539
1,Agiez,57570.916270,45097.04257,42668.61132,23846.87021,39573.64688,54700.99056,44112.448860,24872.27358,23767.179950,...,40740.99966,23071.54294,35189.23270,11695.532970,39316.62263,12680.75438,40558.090660,55378.40648,49257.260150,39076.37149
2,Aigle,1032.805771,12806.69036,14708.57744,33771.21417,18088.76873,21368.31674,56695.504070,33352.86014,34454.957670,...,16930.04614,40987.10347,55753.59043,48135.994080,17633.70500,56957.07744,54895.747330,22576.73176,7553.029716,17932.74595
3,Allaman,47522.552800,40642.39135,38374.06615,19801.74039,37039.86552,56205.38763,16691.436870,18734.80193,18359.219270,...,37720.58416,38296.57183,57357.87610,18123.526940,35369.96791,39739.48966,13193.869580,57358.33950,41726.331610,35386.76027
4,Arnex-sur-Nyon,60116.786400,56346.85466,54368.17988,38281.18622,53708.34720,72658.66608,2880.205603,37046.22329,36845.301450,...,54179.94863,57159.98724,76066.93858,35891.212900,51804.65180,57229.74102,5726.631365,73890.44347,56137.013200,51896.45023

Population clean preview:

            district         commune  commune_code  population_2025
0             Morges          Aclens        5621.0              609
1  Jura-Nord vaudois           Agiez        5742.0              382
2              Aigle           Aigle        5401.0            12081
3             Morges         Allaman        5851.0              412
4               Nyon  Arnex-sur-Nyon        5701.0              274

# Data validation: checking commune names

Before building the optimization model, we need to verify that the commune names are consistent between the two datasets:

1. The distance matrix, which contains the distance from each commune to each hospital.
2. The population dataset, which contains the district and population of each commune.

This step is important because later we will merge both datasets using the commune name.  
If some names do not match, some communes could disappear from the final dataset, and the optimization model would be incorrect.

In this cell, we check:

- whether there are duplicated commune names in the population dataset;
- whether some communes exist in the population dataset but not in the distance matrix;
- whether some communes exist in the distance matrix but not in the population dataset.

In [ ]:
# DATA VALIDATION: CHECK COMMUNE NAMES


# Check duplicated commune names in the population data
duplicated_communes = population_clean[
    population_clean["commune"].duplicated(keep=False)
].sort_values("commune")

print("Duplicated commune rows in population data:")
display(duplicated_communes)


# Check communes that exist in population data but not in distance matrix
communes_population = set(population_clean["commune"])
communes_distance = set(distance_clean["commune"])

missing_in_distance = sorted(communes_population - communes_distance)

print("\nCommunes in population file but missing in distance matrix:")
print(missing_in_distance)
print("Number:", len(missing_in_distance))


# Check communes that exist in distance matrix but not in population data
missing_in_population = sorted(communes_distance - communes_population)

print("\nCommunes in distance matrix but missing in population file:")
print(missing_in_population)
print("Number:", len(missing_in_population))

Duplicated commune rows in population data:

Empty DataFrame
Columns: [district, commune, commune_code, population_2025]
Index: []

Communes in population file but missing in distance matrix:
[]
Number: 0

Communes in distance matrix but missing in population file:
[]
Number: 0